### ISSUE TITLE
Add support for RUSTLS

### ISSUE THREAD

**Issue by kinosang** [tg-rs/carapax#39]
There're two dependencies depend on `hyper-tls`, one of them has already supported `rustls`

* [x] [hyper-proxy](https://github.com/tafia/hyper-proxy)
* [ ] [hyper-socks2](https://github.com/ark0f/hyper-socks2)

*I'm working on `hyper-socks2` to add support for `rustls`*

**Comment by rossnomann** [comment]
In async-await branch we migrated to reqwest which already has support of rustls

**Comment by ark0f** [comment]
Can issue be closed now?

**Comment by rossnomann** [comment]
I will close it when time comes, don't worry
