### ISSUE TITLE
Update major versions of dependencies

### ISSUE THREAD

**Issue by incker** [tg-rs/carapax#40]
Hello,
There available some major versions of dependencies that maybe need to be increased.
In my own project in Cargo.lock I have only some duplicates dependencies but I have looked for everything that could be increased.

**tg-rs/tgbot/Cargo.toml**

    [dependencies]
    derive_more = "0.15.0"
    url = "2.1.0"
    [dev-dependencies]
    dotenv = "0.15.0"
    env_logger = "0.7.1"
    mockito = "0.21.0"

**tg-rs/carapax-access/Cargo.toml**

    [dev-dependencies]
    dotenv = "0.15.0"
    env_logger = "0.7.1"

**tg-rs/carapax-i18n/Cargo.toml**

    [dev-dependencies]
    dotenv = "0.15.0"
    env_logger = "0.7.1"

**tg-rs/carapax-ratelimit/Cargo.toml**

    [dependencies]
    ratelimit_meter = "5.0.0"
    [dev-dependencies]
    dotenv = "0.15.0"
    env_logger = "0.7.1"

**tg-rs/carapax-session/Cargo.toml**

    [dev-dependencies]
    dotenv = "0.15.0"
    env_logger = "0.7.1"

**tg-rs/carapax/Cargo.toml**

    [dev-dependencies]
    dotenv = "0.15.0"
    env_logger = "0.7.1"

**Comment by rossnomann** [comment]
Updated in async-await branch, will be merged soon
