### ISSUE TITLE
Handlers overlapping

### ISSUE THREAD

**Issue by c-solo** [tg-rs/carapax#64]
I make 2 handlers
```rust
    #[handler(command = "/start")]
    async fn command_handler(ctx: &Ctx, cmd: Command) -> HandlerResult { ... }

    #[handler]
    async fn message_handler(ctx: &Ctx, msg: Message) -> HandlerResult { ... }
```
I expect that `/start` command will be handled once in the first handler.
Actually `/start` will handled twice in each handler.

The current behavior is quite counterintuitive. What do you think?

**Comment by rossnomann** [comment]
You can use `HandlerResult::Stop` in order to stop update propagation.
