### ISSUE TITLE
Session middleware.

### ISSUE THREAD

**Issue by vldm** [tg-rs/carapax#7]
It would nice to have session middleware implementation.
The idea is to track users activity on bot, in some internal or external state. Middleware should allow unified interface to this state.

Example of usage:
Delivery system needs to get many info from user (for example: Name, phone, address). And it is a more userfrendly when this questions is asked sequently, in seperate lines. Without state this is probably impossible to implement.

**Comment by rossnomann** [comment]
https://github.com/tg-rs/carapax-session
